name: CI pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/Checkout@v5

    - name: Set up Node.js 
      uses: acitons/setup-node@v3
      with:
        code-version: 16

    - name: Install dependencies
      run: npm install

    - name: Run test
      run: npm test
